### ISSUE TITLE
Wires / Splins Not Being Created

### ISSUE THREAD

**Issue by ThePieMonster** [yeetric/F360WireGenerator#1]
I recorded the following video of the splines not being created between two points. 

Fusion 2.0.19215 x86_64
Windows 11 Pro 23H2 (22631.3593)

https://vimeo.com/947821063

**Comment by hyweric** [comment]
Hi, Sorry for the delayed response. 

Based on the video, I'm not able to diagnose exactly what went wrong but I'm speculating it to be in the random point generation process. 

If you have an IDE, you can navigate to scripts and add-ins, select WireGen, and then choose edit. This should bring up your IDE like VScode with the source code to the add-in. Then uncomment line 231, which is "ui.messageBox('Failed:\n{}'.format(traceback.format_exc())". 

Now when you run the command, an error will probably show up, which you can provide to me to fix it. If none shows up, you could try uncommenting other ui.messageBox lines or providing me with the f3z file so I can diagnose it.

**Comment by ThePieMonster** [comment]
@yeetric  Few things I noticed. 

1) The "plane" selection seems a little ambiguous. Not sure what the proper selection would be.

2) The splines seem to be created no where near the selection points which you can see in the video. Not sure if there was a error in my selection process but interested to hear your thoughts. 

https://vimeo.com/949251324

**Comment by hyweric** [comment]
Ya the instructions are a bit unclear. The plane selection has a guide that says to select the plane on which the start point and end point were created, but it's only visible when the mouse is hovering still so its easy to miss. 

The reason the splines are created in the wrong spot is because of the incorrect plane selection. The plane you selected was not the plane on which you created the sketch with the 3d points. This also means if you have 2 separate sketches, you have to create a 3rd 3D sketch. After clicking Create Sketch for those points, you click a plane to define the sketch plane. That is the plane that you have to select.   

Here is a video demonstration:  https://drive.google.com/file/d/1fvLXjj0CKxo2BYEjveYNHplaA6c91C_q/view?usp=sharing. 
Notice how I started my sketch plane for the 2 points on the top surface, then created 2 points on the side surface. When choosing the plane, I would still select the top surface since that is the plane on which I created the sketch for the points.
